- name: Install Java on Debian/Ubuntu
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Java on RHEL/CentOS/Amazon Linux
  dnf:
    name: java-21-openjdk
    state: present
  when: ansible_facts['os_family'] == "RedHat"


- name: Add Jenkins GPG key (Debian)
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"

- name: Add Jenkins repository (Debian)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
  when: ansible_facts['os_family'] == "Debian"

- name: Install Jenkins (Debian/Ubuntu)
  apt:
    name: jenkins
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

# ---------- RHEL/CentOS/Amazon ----------
- name: Download Jenkins repo file (RHEL)
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'
  when: ansible_facts['os_family'] == "RedHat"

- name: Import Jenkins GPG key (RHEL)
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Jenkins (RHEL/CentOS/Amazon)
  dnf:
    name: jenkins
    state: present
  when: ansible_facts['os_family'] == "RedHat"
